# Generated by Django 2.1.3 on 2018-12-12 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_useranswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='is_correct',
            new_name='is_correctly_answered',
        ),
    ]
