# Generated by Django 2.1.3 on 2019-01-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_auto_20181212_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='user_test_uuid',
            field=models.CharField(default='0000000000000000', max_length=16),
        ),
    ]
